### ISSUE TITLE
Billing Not Saving

### ISSUE THREAD

**Issue by mlim-spring** [sidecars/python-quickbooks#160]
Hi, I'm getting this error when I try to create a bill. I'm not clear what param I am missing. Any help will be very appreciated. This is my error:

```
Traceback (most recent call last):
  File "/Users/maggie/springlabs/git/spring-platform/build/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maggie/springlabs/git/spring-platform/build/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maggie/springlabs/git/spring-platform/build/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/maggie/springlabs/git/spring-platform/build/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/maggie/springlabs/git/spring-platform/build/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maggie/springlabs/git/spring-platform/build/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/maggie/quickbooks/webapp/app/app.py", line 133, in login_sucess
    bill.save(qb = client)
  File "/Users/maggie/springlabs/git/spring-platform/build/lib/python3.7/site-packages/quickbooks/mixins.py", line 147, in save
    json_data = qb.create_object(self.qbo_object_name, self.to_json())
  File "/Users/maggie/springlabs/git/spring-platform/build/lib/python3.7/site-packages/quickbooks/client.py", line 291, in create_object
    results = self.post(url, request_body, file_path=_file_path)
  File "/Users/maggie/springlabs/git/spring-platform/build/lib/python3.7/site-packages/quickbooks/client.py", line 241, in post
    return self.make_request("POST", *args, **kwargs)
  File "/Users/maggie/springlabs/git/spring-platform/build/lib/python3.7/site-packages/quickbooks/client.py", line 230, in make_request
    self.handle_exceptions(result["Fault"])
  File "/Users/maggie/springlabs/git/spring-platform/build/lib/python3.7/site-packages/quickbooks/client.py", line 281, in handle_exceptions
    raise exceptions.ValidationException(message, code, detail)
quickbooks.exceptions.ValidationException: Required param missing, need to supply the required value for the API

```
This is my code:
```
        vendor = Vendor.filter(DisplayName = "Testing", qb = client)[0]
	account = Account.filter(Name = "Test Account monday", qb = client)[0]
	bill = Bill()
	bill.VendorRef = vendor.to_ref
	line = AccountBasedExpenseLine()
	line.Amount = 200
	line.DetailType = "AccountBasedExpenseLineDetail"
	line.Description = "Vendor provided valid data type "
	
	account_ref = Ref()
	account_ref.type = "Account"
	account_ref.value = account.Id

	line.AccountBasedExpenseLineDetail = AccountBasedExpenseLineDetail()
	line.AccountBasedExpenseLineDetail.AccountRef = account_ref
	bill.Line.append(line)

	bill.save(qb = client)
```

**Comment by ej2** [comment]
`bill.VendorRef = vendor.to_ref`
Should be
`bill.VendorRef = vendor.to_ref()`

If that doesn't work, try printing out the json code using the to_json() method on the bill and paste it into the API explorer. Sometimes you can see more detailed error information on the API explorer.

**Comment by mlim-spring** [comment]
That was the exact problem. Don't know how the () got lost in translation. Thank you very much!
