### ISSUE TITLE
"IndexError: list index out of range" at batch.py

### ISSUE THREAD

**Issue by yellow066** [sidecars/python-quickbooks#32]
Hello.

I have created around 100 000 object before an error below.
Do you have idea what could be wrong?

```
Traceback (most recent call last):
  File "bridge.py", line 318, in <module>
    createTransactions()
  File "bridge.py", line 308, in createTransactions
    sendBatch(create_list, command='create')
  File "bridge.py", line 178, in sendBatch
    results = batch_create(batch_list, qb=client)
  File "C:\Users\crs\AppData\Local\Programs\Python\Python35\lib\site-packages\quickbooks\batch.py", line 81, in batch_create
    return batch_mgr.save(obj_list, qb=qb)
  File "C:\Users\crs\AppData\Local\Programs\Python\Python35\lib\site-packages\quickbooks\batch.py", line 23, in save
    result = self.process_batch(temp_list, qb=qb)
  File "C:\Users\crs\AppData\Local\Programs\Python\Python35\lib\site-packages\quickbooks\batch.py", line 38, in process_batch
    batch_response = self.batch_results_to_list(json_data, batch, obj_list)
  File "C:\Users\crs\AppData\Local\Programs\Python\Python35\lib\site-packages\quickbooks\batch.py", line 62, in batch_results_to_list
    batch_item = [obj for obj in batch.BatchItemRequest if obj.bId == response_item.bId][0]
IndexError: list index out of range
```

**Comment by ej2** [comment]
Without having any context, I would guess that 
[obj for obj in batch.BatchItemRequest if obj.bId == response_item.bId] isn't returning anything...
