### ISSUE TITLE
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by m-ajay** [sidecars/python-quickbooks#73]
I'm getting the following error when calling `QuickBooks(**kwargs).get_authorize_url() `method.

Traceback is 

```
>>> qb_object.get_authorize_url()

C:\Users\t0429\projenv\lib\site-packages\requests\packages\urllib3\util\ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an i
ncorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning

C:\Users\t0429\projenv\lib\site-packages\requests\packages\urllib3\util\ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can up
grade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\t0429\projenv\lib\site-packages\quickbooks\client.py", line 159, in get_authorize_url
    params={'oauth_callback': self.callback_url})
  File "C:\Users\t0429\projenv\lib\site-packages\rauth\service.py", line 215, in get_raw_request_token
    **kwargs)
  File "C:\Users\t0429\projenv\lib\site-packages\rauth\session.py", line 210, in request
    return super(OAuth1Session, self).request(method, url, **req_kwargs)
  File "C:\Users\t0429\projenv\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\t0429\projenv\ib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\t0429\projenv\lib\site-packages\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

```
Any hint what am I missing?

**Comment by ej2** [comment]
What version of Python are you using? Could you also post the code where you setup the qb_object?

**Comment by deathnfudge** [comment]
I'm closing this issue since the thread appears dead. Please open a new issue if you are still having issues.

**Comment by vickyonit** [comment]
I am getting the same ssl warning and i am using python 2.7
